version: "3.8"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: general
    networks:
      - postgres

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack exposes services on this port
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./localstack_data/bootstrap:/opt/bootstrap/
      - ./data:/tmp/localstack_data

networks:
  postgres:
    driver: bridge
